- name: Print all extra_vars and job_args
  hosts: all
  gather_facts: false

  tasks:
    # print ALL variables passed to the playbook
    - name: Print all extra_vars and job_args
      debug:
        msg: "{{ item }}"
      loop: "{{ lookup('vars', 'vars') }}"