- name: Print all extra_vars and job_args
  hosts: all
  gather_facts: true

  tasks:
    - name: Print facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print extra_vars
      ansible.builtin.debug:
        var: extra_vars

    - name: Print job_args
      ansible.builtin.debug:
        var: job_args